functional:
 - возможность регистрации с помощью email и пароля
 - возможность авторизации с помощью email и пароля
 - возможность авторизации с помощью своего аккаунта на Github
 - имя пользователя не должно быть пустым
 - имя пользователя не должно быть создано идентичному уже созданному
 - пароль пользователя должен быть не короче 6 символов
 - пароль может содержать только буквы латинского алфавита и цифры
 - пароль должен состоять как минимум из 1 латинской буквы и 1 цифры
 - возможность зайти в свой созданный профиль 
 - возможность переключения языков с английского на русский и наоборот
 - возможность создание игры через кнопку Create a game
 - возможность выбора сложности игры
 - возможность выбора противника (бот, друг, другой участник)
 - возможность выбора времени игры (измеряется в минутах)
 - возможность выбора игры по кодовым словам или выделенным тэгам
 - возможность копирования ссылки созданной игры для приглашения друга
 - возможность присоединиться к уже созданной игре с соперником нажатием кнопки Fight
 - возможность переключения по вкладкам на главной странице - Lobby, Tournament, History
 - возможность выбора языка программирования для участия в игре
 - возможность просматривать ход игры при нажатии кнопки Show
 - возможность писать в общем чате и в чате игры сообщения пользователями
 - возможность переподключения к игре в случае проблем с подключением интернета
 - возможность дописать решение задачи после остановки игры в случае выигрыша противника
 - возможность просмотра своих игр в архиве 
 - возможность получения очков, на основе которых строится рейтинг за неделю, месяц и за все время игры
non-functional:
 - сайт должен быть совместим с мобильными устройствами
 - сайт должен работать на всех ОС (Windows, Mac, Linux)
 - сайт должен быть протестирован на совместимость с последними версиями браузеров
 - сайт должен быть безопасным и защищать данные пользователя
 - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
 - нельзя вносить изменения в таблицу участников
 - нельзя вносить изменения в таблицу лидеров турнира
 - нельзя вмешиваться зрителям в игру - только наблюдение
 - нельзя зрителям помогать в написании кода участников
 - возможность просматривать историю кода доступно только в премиум подписке
 - пользователь не может исправлять собственноручно свой рейтинг в игре и список побед.поражений